          {
            "Tab": "words",
            "Messages": [
                "arse",
                "arsehead",
                "arseheads",
                "arsehole",
                "arseholes",
                "anus",
                "ass",
                "asses",
                "asshat",
                "asshats",
                "assjabber",
                "assjabbers",
                "asspirate",
                "asspirates",
                "assbag",
                "assbags",
                "assbandit",
                "assbandits",
                "assbagger",
                "assbaggers",
                "asshole",
                "asshole",
                "ass holes",
                "assholes",
                "ass bite",
                "ass bites",
                "ass clown",
                "ass clowns",
                "ass cock",
                "ass cocks",
                "ass cracker",
                "ass face",
                "ass faces",
                "ass fuck",
                "ass fucks",
                "ass fucker",
                "ass goblin",
                "ass goblins",
                "ass head",
                "ass heads",
                "ass hopper",
                "ass hoppers",
                "ass jacker",
                "ass jackers",
                "ass lick",
                "ass licker",
                "ass monkey",
                "ass monkeys",
                "ass munch",
                "ass munches",
                "ass munchers",
                "ass nigga",
                "ass niggas",
                "ass nigger",
                "ass niggers",
                "ass shit",
                "ass sucker",
                "ass suckers",
                "ass wad",
                "ass wipe",
                "axwound",
                "bampot",
                "bastard",
                "beaner",
                "beartrap",
                "bitch",
                "bitch ass",
                "bitches",
                "bitch tits",
                "bitch titties",
                "bitchy",
                "blowjob",
                "blowjobs",
                "bollocks",
                "bollox",
                "boner",
                "brotherfucker",
                "bull shit",
                "bumble fuck",
                "butt plug",
                "butt pirate",
                "butt fucka",
                "butt fucker",
                "booty",
                "bugger",
                "bloody",
                "camel toe",
                "carpetmuncher",
                "chesticle",
                "chinc",
                "chink",
                "choad",
                "chode",
                "circlejerk",
                "clit",
                "clitface",
                "clitfuck",
                "clitweasel",
                "clusterfuck",
                "cock",
                "cockass",
                "cockbite",
                "cockblocker",
                "cockburger",
                "cockface",
                "cockfucker",
                "cockhead",
                "cockjockey",
                "cockknoker",
                "cockmaster",
                "cockmongler",
                "cockmongruel",
                "cockmonkey",
                "cockmuncher",
                "cocknose",
                "cocknugget",
                "cockshit",
                "cocksmith",
                "cocksmoke",
                "cocksmoker",
                "cocksniffer",
                "cocksucker",
                "cockwaffle",
                "coochie",
                "coochy",
                "coon",
                "cooter",
                "cracker",
                "cum",
                "cumbubble",
                "cumdumpster",
                "cumguzzler",
                "cumjockey",
                "cumslut",
                "cumtart",
                "cunnie",
                "cunnilingus",
                "cunt",
                "cuntass",
                "cuntbubble",
                "cuntface",
                "cunthole",
                "cuntlicker",
                "cuntrag",
                "cuntslut",
                "dago",
                "damn",
                "deggo",
                "dick",
                "dick sneeze",
                "dickbag",
                "dickbeaters",
                "dickbeater",
                "dickface",
                "dickfuck",
                "dickfucker",
                "dickhead",
                "dickhole",
                "dickjuice",
                "dickmilk",
                "dickmonger",
                "dicks",
                "dickslap",
                "dicksucker",
                "dicksucking",
                "dicktickler",
                "dickwad",
                "dickweasel",
                "dickweed",
                "dickwod",
                "dike",
                "dildo",
                "dipshit",
                "docking",
                "doochbag",
                "dookie",
                "douche",
                "douche fag",
                "douchebag",
                "douchewaffle",
                "dumass",
                "dumb ass",
                "dumbass",
                "dumbfuck",
                "dumbshit",
                "dumshit",
                "dyke",
                "fag",
                "fagbag",
                "fag fucker",
                "faggit",
                "faggot",
                "faggotcock",
                "fagnut",
                "fagtard",
                "fatass",
                "fellatio",
                "feltch",
                "flamer",
                "fuck",
                "fuckass",
                "fuckbag",
                "fuckboy",
                "fuckbrain",
                "fuckbutt",
                "fuckbutter",
                "fucked",
                "fucker",
                "fuckersucker",
                "fuck face",
                "fuckhead",
                "fuckhole",
                "fuckin",
                "fucking",
                "fucknose",
                "fucknut",
                "fucknutt",
                "fuckoff",
                "fucks",
                "fuckstick",
                "fucktard",
                "fucktart",
                "fuckup",
                "fuckwad",
                "fuckwod",
                "fuckwit",
                "fuckwitt",
                "fudgepacker",
                "gay",
                "gayass",
                "gaybob",
                "gaydo",
                "gayfuck",
                "gayfuckist",
                "gaylord",
                "gaytard",
                "gaywad",
                "goddamn",
                "goddamnit",
                "gooch",
                "gook",
                "goopchute",
                "gringo", 
                "guido",
                "handjob", 
                "hard on",
                "heeb", 
                "hell",
                "ho", 
                "hoe",
                "homo", 
                "homodumbshit",
                "honkey", 
                "humping",
                "jackass", 
                "jagoff", 
                "jap", 
                "jerk off", 
                "jerkass", 
                "jigaboo", 
                "jizz", 
                "jungle bunny", 
                "junglebunny", 
                "jungle monkey", 
                "kike", 
                "kooch", 
                "kootch",  
                "kraut", 
                "kunt", 
                "kyke", 
                "lameass", 
                "lardass", 
                "lesbian", 
                "lesbo", 
                "lezzie", 
                "masturbate", 
                "mcfagget", 
                "mick", 
                "minge", 
                "mothafucka",  
                "mothafuckin", 
                "motherfucker", 
                "motherfucking", 
                "muff", 
                "muffdiver", 
                "munging", 
                "nazi", 
                "negro", 
                "nigaboo", 
                "nigga", 
                "nigger", 
                "niggerish", 
                "niggers",  
                "niglet", 
                "nignog", 
                "nut sack", 
                "nutsack", 
                "natzi", 
                "paki", 
                "panooch", 
                "pecker", 
                "peckerhead", 
                "penis", 
                "penisbanger", 
                "penisfucker", 
                "penispuffer",  
                "piss", 
                "pissed", 
                "pissed off", 
                "pissflaps", 
                "polesmoker", 
                "pollock", 
                "poon",  
                "poonani", 
                "poonany", 
                "poontang", 
                "porch monkey", 
                "porchmonkey", 
                "prick", 
                "punanny",  
                "punta", 
                "pussies", 
                "pussy", 
                "pussylicking", 
                "puto", 
                "queef", 
                "queer",  
                "queerbait", 
                "queerhole", 
                "renob", 
                "rimjob", 
                "ruski", 
                "retard", 
                "retigga",  
                "sand nigger", 
                "sandnigger", 
                "schlong", 
                "scrote", 
                "sisterfucker",
                "shit", 
                "shitass", 
                "shitbag",  
                "shitbagger", 
                "shitbrains", 
                "shitbreath", 
                "shitcanned", 
                "shitcunt", 
                "shitdick", 
                "shitface",  
                "shitfaced", 
                "shithead", 
                "shithole", 
                "shithouse", 
                "shitspitter", 
                "shitstain", 
                "shitter",  
                "shittiest", 
                "shitting", 
                "shitty", 
                "shiz", 
                "shiznit", 
                "skank", 
                "skeet",  
                "skullfuck", 
                "slut", 
                "slutbag", 
                "smeg", 
                "snatch", 
                "spic", 
                "spick",  
                "splooge", 
                "spook", 
                "suckass", 
                "tard", 
                "testicle", 
                "thundercunt", 
                "tit",  
                "titfuck", 
                "tits", 
                "tittyfuck", 
                "twat", 
                "twatlips", 
                "twats", 
                "twatwaffle",  
                "twit", 
                "uglyfuck", 
                "unclefucker", 
                "va jj", 
                "vag", 
                "vagina", 
                "vajayjay",  
                "vjayjay", 
                "wank", 
                "wankjob", 
                "wetback", 
                "whore", 
                "whorebag", 
                "whoreface",  
                "wop"
            ]
        }
